block_client:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: glinet
    mac:
      required: true
      example: "aa:bb:cc:dd:ee:ff"
      selector:
        text:
    blocked:
      required: true
      selector:
        boolean:

connect_repeater:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: glinet
    ssid:
      required: true
      selector:
        text:
    password:
      required: false
      selector:
        text:
    identity:
      required: false
      selector:
        text:
    bssid:
      required: false
      example: "aa:bb:cc:dd:ee:ff"
      selector:
        text:

scan_repeater:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: glinet

set_mode:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: glinet
    mode:
      required: true
      selector:
        select:
          options:
          - router
          - ap
    confirm:
      required: true
      selector:
        boolean:

set_wifi:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: glinet
    iface_name:
      required: true
      example: wifi5g
      selector:
        text:
    ssid:
      required: false
      selector:
        text:
    key:
      required: false
      selector:
        text:
    encryption:
      required: false
      selector:
        select:
          options:
          - none
          - psk2
          - psk-mixed
          - sae
          - sae-mixed
    hidden:
      required: false
      selector:
        boolean:
    enabled:
      required: false
      selector:
        boolean:
